version: '3'
services:
   web:
      build:
        context: ./
        args:
          JAR_FILE: /target/demo-0.0.1-SNAPSHOT.jar
      ports:
        - "9000:9000"
      networks:
        mynet:
          ipv4_address: 172.29.0.102
networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.29.0.0/24
